### ISSUE TITLE
--no-sentry option seems to removed from meilisearch

### ISSUE THREAD

**Issue by hexagonhill** [thorian93/ansible-role-meilisearch#2]
Hello,

I am not really across what meilisearch is, I just installed it because I was asked to. Using this role worked fine except for including the --no-sentry argument.
 
https://github.com/meilisearch/MeiliSearch/issues/1606

Thanks.

**Comment by thorian93** [comment]
I am not actively maintaining this role anymore, but I will take a look.
Thanks for your contribution! If you can, feel free to open a pull request. :)

**Comment by thorian93** [comment]
Thanks for the hint!

**Comment by hexagonhill** [comment]
Thanks. The changes is what I had done. I obtained the script form ansible galaxy and thought I would let you know it is not working out of courtesy;  With no expectation it would be fixed.

**Comment by thorian93** [comment]
That's even nicer of you, I appreciate that!
